apiVersion: addon.tvs.io/v1alpha1
kind: AddonConfig
metadata:
  name: antrea-config
spec:
  definitionRef: antrea
  target:
    name: wl-antrea
  values:
    trafficEncapMode: encap
    noSNAT: false
    disableUdpTunnelOffload: false
    defaultMTU: ""
    tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384
    featureGates:
      AntreaProxy: true
      EndpointSlice: true
      AntreaPolicy: true
      FlowExporter: false
      Egress: true
      NodePortLocal: true
      AntreaTraceflow: true
      NetworkPolicyStats: false
      Multicluster: false
      SecondaryNetwork: false
      TrafficControl: false
      AntreaIPAM: false
      ServiceExternalIP: false
      Multicast: false
